 

service: email-processor-v1-python
 
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "sqs:SendMessage"
        - "sqs:GetQueueUrl"
      Resource: 
        - Fn::GetAtt:
            - MyQueue2
            - Arn
    
 
functions:
  receiver2:
    handler: gmailService.lambda_handler
    events:
      - sqs: 
          arn:
            Fn::GetAtt:
              - MyQueue2
              - Arn

resources:
  Resources:
    MyQueue2:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "MyQueue2"